name: Check Source Branch
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  Check_HEAD_Branch:
    runs-on: ubuntu-latest
    steps:
      - name: 📢 Verify BASE and HEAD branches
        shell: pwsh
        run: |
          Write-Host "{{ github.event.pull_request.user.login }}"
