name: Check Source Branch
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
jobs:
  Check_HEAD_Branch:
    runs-on: ubuntu-latest
    steps:
      - name: 📢 Verify BASE and HEAD branches
        run: |
          if [[  ${{ github.base_ref }} == "main" ]]; then
            if [[ ${{ github.head_ref }} =~ ^rc/.*  ||  ${{ github.head_ref }} =~ ^hfc/.* ]]; then
              echo "🚀📣 Ready to merge"
            else
              $body = ">⚠️ Friendly reminder: ⚠️📢 Merge requests to main branch are only allowed from rc/** or hfc/** branches."
              gh pr comment ${{ github.event.pull_request.number }} --repo ${{ github.repository }} --body $body }
              echo "⚠️📢 Merge requests to main branch are only allowed from rc/** or hfc/** branches."
              exit 1
            fi
          fi