name: Check Source Branch
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
jobs:
  Check_HEAD_Branch:
    runs-on: ubuntu-latest
    steps:
      - name: get-team-members
        id: get-members
        shell: pwsh
        run: echo ::set-output name=data::$(gh repo list)
      - name: 📢 Verify BASE and HEAD branches
        run: Write-Host "{{ github.event.pull_request.user.login }}"
