name: Check Source Branch
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  Check_HEAD_Branch:
    runs-on: ubuntu-latest
    steps:
      - name: get-team-members
        id: get-members
        shell: bash
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
          gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /orgs/cmnhospitals/teams

      - name: 📢 Verify BASE and HEAD branches
        run: |
          if [[  ${{ github.base_ref }} == "main" ]]; then
            if [[ ${{ github.head_ref }} =~ ^rc/.*  ||  ${{ github.head_ref }} =~ ^hfc/.* ]]; then
              echo "🚀📣 Ready to merge"
            else { body = ">⚠️ Friendly reminder: ⚠️📢 Merge requests to main branch are only allowed from rc/** or hfc/** branches."; echo "$(body)"; exit 1; }
            fi
          fi
