name: Check pull request source branch
on:
  workflow_dispatch:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
jobs:
  check-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Check branches
        run: |
          if [[ ! ${{ github.head_ref }} =~ ^rc/.* ] || [ ! ${{ github.head_ref }} =~ ^hfc/.* ]] && [ ${{ github.base_ref }} == "main" ]; then
            echo "📣📢 Merge requests to main branch are only allowed from rc/** branches."
            exit 1
          else
            echo "🚀📣 Ready to merge!"
          fi
